# Generated by Django 4.0.4 on 2022-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_group1_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group1',
            name='group_name',
            field=models.CharField(default='CRSDSTTCDTHGAML', max_length=20, unique=True),
        ),
    ]
