# Generated by Django 4.0.4 on 2022-05-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_group1_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=20)),
                ('usr_surname', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('phone_num', models.IntegerField(null=True)),
                ('gender', models.CharField(default='Other', max_length=7)),
                ('password', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='group1',
            name='group_name',
            field=models.CharField(default='UDNCKTGEANOIOHH', max_length=20, unique=True),
        ),
    ]
